name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foundry-rs/foundry:latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: forge install
      - name: forge
        run: forge test -vvvv
