name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foundry-rs/foundry:latest
    steps:
      - uses: actions/checkout@v3
      - name: ls
        run: ls
      - name: forge
        run: forge test --root /github/workspace/

# docker run -v $PWD:/app foundry "forge test --root /app --watch"
