name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foundry-rs/foundry:latest
    steps:
      - name: install git
        run: apk add git
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: forge
        run: forge test -vvvv
